/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-background": "#e4e1ed",
        "surface-container-low": "#1b1b23",
        "outline-variant": "#464554",
        "tertiary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#c7c4d7",
        "error": "#ffb4ab",
        "secondary-container": "#571bc1",
        "secondary-fixed-dim": "#d0bcff",
        "surface-container-lowest": "#0d0d15",
        "surface-bright": "#393841",
        "primary": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-surface": "#e4e1ed",
        "on-primary-container": "#0d0096",
        "tertiary-container": "#4d8eff",
        "on-tertiary": "#002e6a",
        "surface-container-highest": "#34343d",
        "inverse-surface": "#e4e1ed",
        "error-container": "#93000a",
        "secondary": "#d0bcff",
        "background": "#13131b",
        "surface": "#13131b",
        "tertiary-fixed": "#d8e2ff",
        "inverse-primary": "#494bd6",
        "surface-container": "#1f1f27",
        "surface-tint": "#c0c1ff",
        "on-secondary-fixed": "#23005c",
        "surface-variant": "#34343d",
        "primary-container": "#8083ff",
        "on-tertiary-container": "#00285d",
        "on-tertiary-fixed-variant": "#004395",
        "secondary-fixed": "#e9ddff",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-fixed": "#001a42",
        "on-secondary": "#3c0091",
        "surface-dim": "#13131b",
        "tertiary": "#adc6ff",
        "on-primary": "#1000a9",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#c4abff",
        "outline": "#908fa0",
        "surface-container-high": "#292932",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#5516be",
        "inverse-on-surface": "#303038",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#2f2ebe"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        label: ["Geist", "sans-serif"],
        code: ["Geist", "monospace"],
        body: ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
